<?php $__env->startSection('title'); ?>
    <?php echo e(__('Security')); ?>

<?php $__env->stopSection(); ?>

<?php $__env->startSection('content'); ?>
    <div class="card border-primary mb-3">
        <div class="card-body">
            <h5 class="card-title"><?php echo e(__('Two-factor authentication')); ?></h5>
            <p class="text-muted">
                <?php echo e(__('2-step verification provides stronger security for your account by requiring a second step of verification when you sign in.')); ?>

                <?php echo e(__('In addition to your password, you will also need a code generated by the Google Authenticator app on your phone.')); ?>

                <?php echo e(__('It is strongly recommended to enable two-factor authentication to protect your account.')); ?>

            </p>
            <?php if(auth()->user()->totp_secret): ?>
                <a href="<?php echo e(route('frontend.security.2fa.disable')); ?>" class="btn btn-danger"><?php echo e(__('Disable 2FA')); ?></a>
            <?php else: ?>
                <a href="<?php echo e(route('frontend.security.2fa.enable')); ?>" class="btn btn-primary"><?php echo e(__('Enable 2FA')); ?></a>
            <?php endif; ?>
        </div>
    </div>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('frontend.layouts.main', \Illuminate\Support\Arr::except(get_defined_vars(), array('__data', '__path')))->render(); ?>